### ISSUE TITLE
[BROKEN]

### ISSUE THREAD

**Issue by iamsaalim** [realme-kernel-opensource/realme3-3i-AndroidQ-kernel-source#1]
did ya tried to build source before uploading

**Comment by adi8900** [comment]
Haha no

**Comment by CryllicBuster273** [comment]
> did ya tried to build source before uploading

Obviously no 🤣🤣🤣🤣

**Comment by realme-kernel-opensource** [comment]
hi,sir:
we had compiled this kernel source code.
pls specify the detail about compile error messages.we will check it futher.

**Comment by adi8900** [comment]
Wen proper history

**Comment by iamsaalim** [comment]
https://del.dog/limerippyl.txt
