### ISSUE TITLE
[SAD]

### ISSUE THREAD

**Issue by iamsaalim** [realme-kernel-opensource/realme3-3i-AndroidQ-kernel-source#3]
you made realme3 community sad by giving this shit af source

**Comment by Remicaa** [comment]
💔 😭

**Comment by denomparkour** [comment]
> you made realme3 community sad by giving this shit af source

Bruh veri sad

**Comment by starlight5234** [comment]
> teach realme bringup wen

Sar u pero u do bringup wen

**Comment by iamsaalim** [comment]
Me nub

**Comment by starlight5234** [comment]
> Me nub

Me ultra ghei nub then

**Comment by Aoihara** [comment]
> Me nub

U do help realmeme bringup plox xD

**Comment by denomparkour** [comment]
> Me nub

Bruh u pro
Gib iOS for realmeme

**Comment by starlight5234** [comment]
> > Me nub
> 
> Bruh u pro
> Gib iOS for realmeme

TRUE VERI FUKIN TRUE btw he making SaalimOS. Very Pro

**Comment by CryllicBuster273** [comment]
> > > Me nub
> > 
> > 
> > Bruh u pro
> > Gib iOS for realmeme
> 
> TRUE VERI FUKIN TRUE btw he making SaalimOS. Very Pro

SaalimOS will be based on Kernel version 5.7 which will be much better than realmeme kernel sauce 😂😂

**Comment by baibhab34** [comment]
> you made realme3 community sad by giving this shit af source

We're sad too when they're gonna release a10 kernel sources

**Comment by denomparkour** [comment]
> teach realme bringup wen

SaalimOS wen?

**Comment by baibhab34** [comment]
> > teach realme bringup wen
> 
> SaalimOS wen?

It's already in testing

**Comment by denomparkour** [comment]
> > > teach realme bringup wen
> > 
> > 
> > SaalimOS wen?
> 
> It's already in testing

Very nais

**Comment by starlight5234** [comment]
> > > > Me nub
> > > 
> > > 
> > > Bruh u pro
> > > Gib iOS for realmeme
> > 
> > 
> > TRUE VERI FUKIN TRUE btw he making SaalimOS. Very Pro
> 
> SaalimOS will be based on Kernel version 5.7 which will be much better than realmeme kernel sauce

Yes Soon™🤗
